//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmBio1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int ID { get; set; }
        public int visningsID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Email { get; set; }
        public string Auditorium { get; set; }
        public Nullable<int> Seats { get; set; }
    }
}
